spring:
  datasource:
    url: jdbc:mysql://sh-cynosdbmysql-grp-38086q0k.sql.tencentcdb.com:26809/dni?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Fan20011001
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
anuen:
  auth:
    excludePath:
      - /api/user/login
      - /api/patient/add
      - /api/search/**
  jwt:
    location: classpath:jwt.jks
    algorithm: rs256
    alias: jwt
    password: 20011001
    tokenTTL: 30m
